### ISSUE TITLE
Generating a sequelize service backed by NeDB causes app to throw.

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/cli#109]
I added a Sequelize service and chose NeDB (!) as the database. The app threw when I started it.

```text
/home/johnsz/shared/repos/feathers-test/test-app/node_modules/sequelize/lib/sequelize.js:111
      options.dialect = urlParts.protocol.replace(/:$/, '');
                                         ^

TypeError: Cannot read property 'replace' of null
    at new Sequelize (/home/johnsz/shared/repos/feathers-test/test-app/node_modules/sequelize/lib/sequelize.js:111:42)
    at EventEmitter.module.exports (/home/johnsz/shared/repos/feathers-test/test-app/src/sequelize.js:6:21)
    at EventEmitter.configure (/home/johnsz/shared/repos/feathers-test/test-app/node_modules/feathers/lib/application.js:138:8)
```

The sequelize.model.js runs
```js
const sequelizeClient = app.get('sequelizeClient');
```
but that has not been created in `config/default.json`.

**Comment by eddyystop** [comment]
Actually the database selection is messed up. All the DBs are offered in a seeminly endless list.

**Comment by eddyystop** [comment]
Then I created a Sequelize service using SQLite. `config/default.json` contained `"sqlite": "sqlite://test_app.sqlite"`.

The app threw in the same place when I started it
```js
/home/johnsz/shared/repos/feathers-test/test-app/node_modules/sequelize/lib/sequelize.js:111
      options.dialect = urlParts.protocol.replace(/:$/, '');
                                         ^

TypeError: Cannot read property 'replace' of null
    at new Sequelize (/home/johnsz/shared/repos/feathers-test/test-app/node_modules/sequelize/lib/sequelize.js:111:42)
    at EventEmitter.module.exports (/home/johnsz/shared/repos/feathers-test/test-app/src/sequelize.js:6:21)
```

**Comment by daffl** [comment]
That's how inquirer does its lists. But you are right, the options list should be limited to valid databases.

**Comment by ruslankonev** [comment]
I have the same bug. What I need to do?

**Comment by daffl** [comment]
Choose one of the databases [Sequelize supports](http://docs.sequelizejs.com/).

**Comment by daffl** [comment]
This issue was moved to feathersjs/feathers#953
