### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by bitflower** [feathersjs/cli#145]
### Steps to reproduce

Hey fellas, been into Feathers for like 1-2 months and now (!) I'm starting to feel the need for some little helpers ;-) First try of the cli gave me this though:

```terminal
mmm:caseos-server matthias$ npm install -g @feathersjs/cli
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
/Users/matthias/.nvm/versions/node/v8.9.4/bin/feathers -> /Users/matthias/.nvm/versions/node/v8.9.4/lib/node_modules/@feathersjs/cli/bin/feathers.js
+ @feathersjs/cli@3.6.1
added 412 packages from 218 contributors in 13.629s
```

```terminal
mmm:caseos-server matthias$ feathers generate service
? What kind of service is it? A custom service
? What is the name of the service? mailer
? Which path should the service be registered on? /mailer
? Does the service require authentication? No
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: /Users/matthias/Documents/Projekte/bitflower/Case OS/Prototype/v0.2/caseos-server/src/services/index.js doesn't exist
    at EditionInterface.module.exports [as read] (/Users/matthias/.nvm/versions/node/v8.9.4/lib/node_modules/@feathersjs/cli/node_modules/mem-fs-editor/lib/actions/read.js:12:11)
    at ServiceGenerator.writing (/Users/matthias/.nvm/versions/node/v8.9.4/lib/node_modules/@feathersjs/cli/node_modules/generator-feathers/generators/service/index.js:152:17)
    at Object.<anonymous> (/Users/matthias/.nvm/versions/node/v8.9.4/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:399:25)
    at /Users/matthias/.nvm/versions/node/v8.9.4/lib/node_modules/@feathersjs/cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/matthias/.nvm/versions/node/v8.9.4/lib/node_modules/@feathersjs/cli/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/matthias/.nvm/versions/node/v8.9.4/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:400:11)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Clean `npm i` of the cli.

Any ideas?

**NodeJS version**:
8.9.4

**Operating System**:
macOS 10.13

**Comment by daffl** [comment]
Like the error message says, does `src/services/index.js` exist and is writable?

**Comment by bitflower** [comment]
I'm using typescript. It seemed so "heavy" that I didn't think of this. Sorry, for stealing your time !

Apart from that, any chance to make it a `.js | .ts` kinda detection? Although that might lead to others problems when TS has different synthax, more lines, types, etc....

Hm, shame!

**Comment by daffl** [comment]
Unfortunately probably not any time soon. You can follow the TypeScript generator issue at https://github.com/feathersjs/cli/issues/114
