### ISSUE TITLE
CLI switch for version number does not work. Possible bug

### ISSUE THREAD

**Issue by kokujin** [feathersjs/cli#150]
On a fresh install of node, I decided to upgrade the feathers CLI application, I wanted to check if all went well so I tried to view the version number. using "-V" and "--version" and I got the error below

`````
╰─$ feathers --version                                                     1 ↵
path.js:1086
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1086:25)
    at Function.Module._resolveLookupPaths (internal/modules/cjs/loader.js:457:17)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:564:20)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/kokujin/.nvm/versions/node/v10.1.0/lib/node_modules/@feathersjs/cli/bin/feathers.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
`````

**Comment by daffl** [comment]
I can't reproduce this with Node 10.1. This error usually means that you are trying to run the command from a deleted or moved directory.

**Comment by kokujin** [comment]
I switched between versions using nvm again and decided to restart my computer. It seems to be ok now
