### ISSUE TITLE
Error when using NodeJS 10.6.0

### ISSUE THREAD

**Issue by forgot** [feathersjs/cli#157]
### Steps to reproduce

1) Use the latest version of NodeJS (v10.6.0)
2) Install the latest version of Feathers CLI (v3.7.3)
3) Create a new project directory, and run `feathers generate app`.

**_Note: If I switch to NodeJS v10.5.0, everything works just fine._**

### Expected behavior
It should start generating a new app.

### Actual behavior
This...
```
/Users/forgot/.nvm/versions/node/v10.6.0/lib/node_modules/@feathersjs/cli/node_modules/hosted-git-info/index.js:73
      if (!(ex instanceof URIError)) throw ex
                                     ^

TypeError: Cannot read property 'replace' of null
    at /Users/forgot/.nvm/versions/node/v10.6.0/lib/node_modules/@feathersjs/cli/node_modules/hosted-git-info/index.js:61:63
    at Array.map (<anonymous>)
    at fromUrl (/Users/forgot/.nvm/versions/node/v10.6.0/lib/node_modules/@feathersjs/cli/node_modules/hosted-git-info/index.js:45:39)
    at Function.module.exports.fromUrl (/Users/forgot/.nvm/versions/node/v10.6.0/lib/node_modules/@feathersjs/cli/node_modules/hosted-git-info/index.js:32:18)
    at Object.<anonymous> (/Users/forgot/.nvm/versions/node/v10.6.0/lib/node_modules/@feathersjs/cli/node_modules/normalize-package-data/lib/fixer.js:150:36)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/forgot/.nvm/versions/node/v10.6.0/lib/node_modules/@feathersjs/cli/node_modules/normalize-package-data/lib/fixer.js:144:31)
    at Array.forEach (<anonymous>)
    at Object.fixDependencies (/Users/forgot/.nvm/versions/node/v10.6.0/lib/node_modules/@feathersjs/cli/node_modules/normalize-package-data/lib/fixer.js:137:41)
    at /Users/forgot/.nvm/versions/node/v10.6.0/lib/node_modules/@feathersjs/cli/node_modules/normalize-package-data/lib/normalize.js:32:38
    at Array.forEach (<anonymous>)
    at normalize (/Users/forgot/.nvm/versions/node/v10.6.0/lib/node_modules/@feathersjs/cli/node_modules/normalize-package-data/lib/normalize.js:31:15)
    at Function.module.exports.sync (/Users/forgot/.nvm/versions/node/v10.6.0/lib/node_modules/@feathersjs/cli/node_modules/read-pkg/index.js:43:36)
    at Function.module.exports.sync.options [as sync] (/Users/forgot/.nvm/versions/node/v10.6.0/lib/node_modules/@feathersjs/cli/node_modules/read-pkg-up/index.js:23:16)
    at AppGenerator.rootGeneratorName (/Users/forgot/.nvm/versions/node/v10.6.0/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:552:27)
    at AppGenerator._getStorage (/Users/forgot/.nvm/versions/node/v10.6.0/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:572:29)
```

### System configuration

**Module versions** (especially the part that's not working):
Latest Feathers CLI release (v3.7.3)

**NodeJS version**:
10.6.0

**Operating System**:
macOS 10.13.3

**Comment by daffl** [comment]
I just tried with Node v10.6.0 and `@featherjs/cli` v3.7.3 on Mac OS 10.13.5 and can not reproduce the issue.

**Comment by forgot** [comment]
I'm not sure what to tell you then...

I've tried completely removing `@feathers/cli` from `npm`, and reinstalling it. If I'm on Node v10.6.0, I get that error every time. If I switch back to v10.5.0, it works like a champ. 

I'll try updating to macOS 10.13.5 and see if that helps.

**Comment by daffl** [comment]
I'm going to close this. We can revisit if this issue happens for someone else or is easily reproducible.
