### ISSUE TITLE
feathers generate for sequelize service throws unhandled 'error' event

### ISSUE THREAD

**Issue by RNG-Tech** [feathersjs/cli#176]
### Expected behavior
Should generate feathers sequelize service 'test'

### Actual behavior
```
? What kind of service is it? Sequelize
? What is the name of the service? test
? Which path should the service be registered on? /test
events.js:173
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'jest' of undefined
    at ServiceGenerator.writing (C:\Users\User\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\generator-feathers\generators\service\index.js:142:45)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\yeoman-generator\lib\index.js:424:27)
    at C:\Users\User\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\User\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\User\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\yeoman-generator\lib\index.js:425:13)
    at processImmediate (timers.js:637:19)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\User\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\yeoman-generator\lib\index.js:433:22)
    at processImmediate (timers.js:637:19)
```

### System configuration

**Module versions** (especially the part that's not working):

Global:
`"@feathersjs/cli": "^3.9.0"`

Project:
```
"@feathersjs/configuration": "^2.0.6",
"@feathersjs/errors": "^3.3.6",
"@feathersjs/express": "^1.3.1",
"@feathersjs/feathers": "^3.3.1",
"@feathersjs/socketio": "^3.2.9",
"feathers-sequelize": "^5.1.3",
"helmet": "^3.16.0",
"mysql2": "^1.6.5",
"sequelize": "^5.7.4"
```
**NodeJS version**: 
11.11.0

**Operating System**:
Windows 10 (64Bit)

**Comment by daffl** [comment]
`feathers generate app` has to be run first (with the same version of the generator) to have a generated application available.

**Comment by franzherzog** [comment]
This seems to be a problem with the feathers-generator.
If you have no devDependency in your package.json the check in feathers-generator for jest will fail with an undefined object.
this line -> https://github.com/feathersjs/generator-feathers/blob/master/lib/generator.js#L40
temp fix: 
```npm install --save-dev jest```
