### ISSUE TITLE
feathers cli v4 upgrade error

### ISSUE THREAD

**Issue by apmcodes** [feathersjs/cli#189]
### Steps to reproduce

Upgraded feathers cli from v3.9 to v4.x.
Now feathers upgrade gives the following error

### Expected behavior
Upgarde feathers from v3 to v4

### Actual behavior

```
$ feathers upgrade
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property 'authentication' of undefined
    at UpgradeGenerator.writing (/home/xxx/.nvm/versions/node/v10.13.0/lib/node_modules/@feathersjs/cli/node_modules/generator-feathers/generators/upgrade/index.js:15:27)
    at Object.<anonymous> (/home/xxx/.nvm/versions/node/v10.13.0/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:427:27)
    at /home/xxx/.nvm/versions/node/v10.13.0/lib/node_modules/@feathersjs/cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/xxx/.nvm/versions/node/v10.13.0/lib/node_modules/@feathersjs/cli/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/xxx/.nvm/versions/node/v10.13.0/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:428:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/home/xxx/.nvm/versions/node/v10.13.0/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:436:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

```

tried manually updating src/authentication.js as per the migration doc ...

**Comment by daffl** [comment]
This should already be fixed in `@feathersjs/cli@v4.1.1`

**Comment by daffl** [comment]
Closing since the issue has been open for a while without any new information. Please feel free to reopen with more information at any time 😄

**Comment by loki-sama** [comment]
I have the same issue with @feathersjs/cli@4.1.1

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property 'authentication' of undefined
    at UpgradeGenerator.writing (/Users/xxx/.nvm/versions/node/v10.15.3/lib/node_modules/@feathersjs/cli/node_modules/generator-feathers/generators/upgrade/index.js:15:27)
    at Object.<anonymous> (/Users/xxx/.nvm/versions/node/v10.15.3/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:427:27)
    at /Users/xxx/.nvm/versions/node/v10.15.3/lib/node_modules/@feathersjs/cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/xxx/.nvm/versions/node/v10.15.3/lib/node_modules/@feathersjs/cli/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/xxx/.nvm/versions/node/v10.15.3/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:428:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/xxx/.nvm/versions/node/v10.15.3/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:436:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by apmcodes** [comment]
> Closing since the issue has been open for a while without any new information. Please feel free to reopen with more information at any time

Okay sure. Will be upgrading feathers in few days. Juggling with 5 FeathersJs microservice apps.  :))
