### ISSUE TITLE
feathersjs v4 after upgrade to typescript getting services\index.js doesn't exist error

### ISSUE THREAD

**Issue by saravanakumargn** [feathersjs/cli#194]
### Expected behavior
Not able to generate new Service after migrating manually from v3 to v4 (From js to typescript). This command `feathers generate service` is try to find index.js file but this file is replaced by index.ts. Please let me know if I missed any configurations.

### Actual behavior
```
λ feathers generate service
? What kind of service is it? Mongoose
? What is the name of the service? reports
? Which path should the service be registered on? /reports
? Does the service require authentication? Yes
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: E:\projects\my-app\app-api\src\services\index.js doesn't exist
    at EditionInterface.module.exports [as read] (C:\Users\MyApp\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\mem-fs-editor\lib\actions\read.js:12:11)
    at ServiceGenerator.writing (C:\Users\MyApp\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\generator-feathers\generators\service\index.js:172:19)
    at Object.<anonymous> (C:\Users\MyApp\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\yeoman-generator\lib\index.js:395:23)
    at C:\Users\MyApp\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\MyApp\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\MyApp\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\yeoman-generator\lib\index.js:396:9)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\MyApp\AppData\Roaming\npm\node_modules\@feathersjs\cli\node_modules\yeoman-generator\lib\index.js:404:18)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by daffl** [comment]
To determine the application language the generator will look if your `pacakage.json` has a `"types": "lib/" field. If you add it the proper files will be generated.

**Comment by karluqs** [comment]
Hi,

This problem is happing when using node v16.4.2, my package.json has the `"types": "lib/" field

When using node v14.15.1 it works fine.

i'm using a macbook (bigSur), the node 16 was installed using nvm 

```
/Users/myuser/.nvm/versions/node/v16.4.2/lib/node_modules/feathers-cli/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/read.js:12
    throw new Error(filepath + ' doesn\'t exist');
          ^

Error: /Users/myuser/git/project/src/services/index.js doesn't exist
    at EditionInterface.module.exports [as read] (/Users/myuser/.nvm/versions/node/v16.4.2/lib/node_modules/feathers-cli/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/read.js:12:11)
    at ServiceGenerator.writing (/Users/myuser/.nvm/versions/node/v16.4.2/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/service/index.js:147:17)
    at Object.<anonymous> (/Users/myuser/.nvm/versions/node/v16.4.2/lib/node_modules/feathers-cli/node_modules/yeoman-generator/lib/index.js:399:25)
    at /Users/myuser/.nvm/versions/node/v16.4.2/lib/node_modules/feathers-cli/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/myuser/.nvm/versions/node/v16.4.2/lib/node_modules/feathers-cli/node_modules/run-async/index.js:26:19
    at /Users/myuser/.nvm/versions/node/v16.4.2/lib/node_modules/feathers-cli/node_modules/yeoman-generator/lib/index.js:400:11
```
