### ISSUE TITLE
feather cli v4 upgrade error

### ISSUE THREAD

**Issue by shtrived** [feathersjs/cli#209]
**Steps to reproduce**
Upgraded feathers cli from v3.9 to v4.x.
Now feathers upgrade gives the following error

**Expected behavior**
Upgrade feathers from v3 to v4

**Actual behavior**
```
events.js:200
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1039:7)
    at UpgradeGenerator.destinationPath (/Users/foo/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:869:30)
    at UpgradeGenerator.writing (/Users/foo/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/generator-feathers/generators/upgrade/index.js:49:27)
    at Object.<anonymous> (/Users/foo/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:546:23)
    at /Users/foo/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/foo/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/run-async/index.js:24:19
    at /Users/foo/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:547:9
    at processImmediate (internal/timers.js:439:21)
Emitted 'error' event on UpgradeGenerator instance at:
    at Immediate.<anonymous> (/Users/foo/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/yeoman-generator/lib/index.js:559:18)
    at processImmediate (internal/timers.js:439:21) {
  code: 'ERR_INVALID_ARG_TYPE'
```

**Comment by daffl** [comment]
The upgrade command will only work for applications generated with the v3 CLI. This problem usually occurs then the `directories` are not set properly in `package.json` (see https://github.com/feathersjs/feathers-chat/blob/master/package.json#L16 for how it should look like). Manual upgrade should still be possible as outlined in [the migration guide](https://docs.feathersjs.com/guides/migrating.html).
