### ISSUE TITLE
Build tools in typescript throw error in Node 14.1

### ISSUE THREAD

**Issue by roemhildtg** [feathersjs/cli#227]
### Steps to reproduce

I'm running into this error with a clean install of a feathers app:

```
❯ npm run dev

> feathers-test@0.0.0 dev /home/gregg/Projects/feathers-test
> ts-node-dev --no-notify src/

Using ts-node version 8.10.1, typescript version 3.8.3
TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at Object.watch (fs.js:1441:11)
    at add (/home/gregg/Projects/feathers-test/node_modules/filewatcher/index.js:74:34)
    at /home/gregg/Projects/feathers-test/node_modules/filewatcher/index.js:93:5
    at FSReqCallback.oncomplete (fs.js:176:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! feathers-test@0.0.0 dev: `ts-node-dev --no-notify src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the feathers-test@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gregg/.npm/_logs/2020-05-07T02_10_29_080Z-debug.log
 ~/Projects/feathers-test    
```

After the crash - I see a nodejs process running consuming 100% of a single core until I force kill the task. 

### Expected behavior
`npm run dev` should continue to build the project and watch for changes.

### Actual behavior
Instead it throws the error and creates a node process. 

### System configuration

Manjaro 20.0 x64
Nodejs 14.1.0
npm 6.14.4
feathers-cli 4.3.0

**Module versions** (especially the part that's not working):

    "@feathersjs/authentication-client": "^4.5.4",
    "@feathersjs/configuration": "^4.5.2",
    "@feathersjs/errors": "^4.5.2",
    "@feathersjs/express": "^4.5.2",
    "@feathersjs/feathers": "^4.5.3",
    "@feathersjs/rest-client": "^4.5.3",
    "@feathersjs/socketio": "^4.5.2",
    "@feathersjs/socketio-client": "^4.5.4",
    "@feathersjs/transport-commons": "^4.5.2",

    "@types/compression": "^1.7.0",
    "@types/config": "^0.0.36",
    "@types/cors": "^2.8.6",
    "@types/debug": "^4.1.5",
    "@types/helmet": "0.0.45",
    "@types/isomorphic-fetch": "^0.0.35",
    "@types/isomorphic-form-data": "^2.0.0",
    "@types/jest": "^25.2.1",
    "@types/lodash.get": "^4.4.6",
    "@types/lodash.omit": "^4.5.6",
    "@types/mkdirp": "^1.0.0",
    "@types/multer": "^1.4.3",
    "@types/nodemon": "^1.19.0",
    "@types/prettier": "^2.0.0",
    "@types/rimraf": "^3.0.0",
    "@types/serve-favicon": "^2.5.0",
    "@types/sqlite3": "^3.1.6",
    "@types/uuid": "^7.0.2",
    "axios": "^0.19.2",
    "jest": "^25.3.0",
    "nodemon": "^2.0.3",
    "prettier": "^2.0.4",
    "shx": "^0.3.2",
    "ts-jest": "^25.3.1",
    "ts-node-dev": "^1.0.0-pre.44",
    "tslint": "^5.20.1",
    "typescript": "^3.8.3"

**Comment by roemhildtg** [comment]
I'm going to close this since it appears to be an issue with ts-node-dev

https://github.com/whitecolor/ts-node-dev/issues/143
