### ISSUE TITLE
Exception when generating hooks

### ISSUE THREAD

**Issue by DaCookie** [feathersjs/cli#234]
### Steps to reproduce

I'm discovering the Feathers framework, by following [the official guides](https://docs.feathersjs.com/guides/basics/generator.html). At [the Hooks step](https://docs.feathersjs.com/guides/basics/hooks.html#hooks), an error occurs when I run the `feathers generate hook` command.

This is a regression, since I get the error on `@featherjs/cli@4.4.0`, but the command works well on `@featherjs/cli@4.3.0`.

### Expected behavior

After answering the questions, it should generate a `src/hooks/process-message.hooks.ts` file, and update the `src/services/messages/messages.hooks.ts` file.

### Actual behavior

I get this `SyntaxError` exception:

```txt
feathers generate hook
? What is the name of the hook? process-message
? What kind of hook should it be? before
? What service(s) should this hook be for (select none to add it yourself)?
 messages
? What methods should the hook be for (select none to add it yourself)? create

(node:15112) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token, expected "," (13:26)
    at Object._raise (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:763:17)
    at Object.raiseWithData (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:756:17)    
    at Object.raise (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:750:17)
    at Object.unexpected (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:8930:16)      
    at Object.expect (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:8916:28)
    at Object.parseBindingList (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:9305:14)
    at Object.parseFunctionParams (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:12093:24)
    at Object.parseFunction (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:12068:10)
    at Object.parseFunctionStatement (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:11696:17)
    at Object.parseStatementContent (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:11386:21)
    at Object.parseStatement (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:11348:17)
    at Object.parseBlockOrModuleBlockBody (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:11930:25)
    at Object.parseBlockBody (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:11916:10)
    at Object.parseBlockBody (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:892:11)
    at Object.parseTopLevel (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:11279:10)
    at Object.parse (\npm\node_modules\@feathersjs\cli\node_modules\@babel\parser\lib\index.js:12984:10)
(node:15112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### System configuration

**Module versions** (especially the part that's not working): `@feathers/cli@4.4.0`

**NodeJS version**: v12.14.1

**Operating System**: Windows

**Comment by NoahWallace** [comment]
I am running into the same issue on Mac with
@feathersjs/cli@4.4.2
node: v12.14.1
`(node:22775) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token, expected "," (17:10)
    at Object._raise (/Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:790:17)
    at Object.raiseWithData (/Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:783:17)
    at Object.raise (/Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:777:17)
    at Object.unexpected (/Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:9095:16)
    at Object.expect (/Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:9081:28)
    at Object.parseParenAndDistinguishExpression (/Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:10690:14)
    at Object.parseExprAtom (/Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:10424:21)
    at Object.parseExprAtom (/Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:949:22)
    at Object.parseExprAtom (/Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:4759:20)
    at Object.parseExprSubscripts (/Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:10094:23)
    at Object.parseUpdate (/Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:10074:21)
    at Object.parseMaybeUnary (/Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:10063:17)
    at Object.parseExprOps (/Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:9933:23)
    at Object.parseMaybeConditional (/Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:9907:23)
    at Object.parseMaybeAssign (/Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:9870:21)
    at /Users/noah/.nvm/versions/node/v12.14.1/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:9837:39
(node:22775) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22775) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by daffl** [comment]
This should now be fixed in the latest version.
