### ISSUE TITLE
CLI service generation crash when the name start by a number

### ISSUE THREAD

**Issue by soullivaneuh** [feathersjs/cli#279]
### Steps to reproduce

```
❯ feathers g service
? What kind of service is it? A custom service
? What is the name of the service? 3ds
? Which path should the service be registered on? /3ds
? Does the service require authentication? No
```

### Expected behavior

A generated service named `3ds`

### Actual behavior

```
/usr/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:807
    const err = new SyntaxError(message);
                ^

SyntaxError: Identifier directly after number. (1:8)
    at Object._raise (/usr/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:807:17)
    at Object.raiseWithData (/usr/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:800:17)
    at Object.raise (/usr/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:761:17)
    at Object.readNumber (/usr/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:2587:18)
    at Object.getTokenFromCode (/usr/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:2281:14)
    at Object.getTokenFromCode (/usr/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:7207:18)
    at Object.nextToken (/usr/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:1759:12)
    at Object.next (/usr/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:1665:10)
    at Object.parseStatementContent (/usr/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:12922:16)
    at Object.parseStatement (/usr/lib/node_modules/@feathersjs/cli/node_modules/@babel/parser/lib/index.js:12826:17) {
  loc: Position { line: 1, column: 8 },
  pos: 8,
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'NumberIdentifier'
}
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

```
❯ feathers --version                 
4.5.0
```

**NodeJS version**:

```
❯ node -v
v15.10.0
```

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by soullivaneuh** [comment]
Ok I understood why: The generated class name start by a number. That is not valid.

But it is ok to have a string name and a path starting by a number, as far as I know. :wink: 

However, I am currently not very sure about what solution to give to that problem.

**Comment by daffl** [comment]
You should just be able to enter a different `name` and type the path you want explicitly:

> ? What is the name of the service? __ThreeDs__
> ? Which path should the service be registered on? __/3ds__
